name: lkg-quilt
channels:
  - conda-forge
dependencies:
  - aom=3.7.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - dav1d=1.2.1
  - expat=2.5.0
  - ffmpeg=6.1.0
  - ffmpeg-python=0.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - gettext=0.21.1
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - harfbuzz=8.3.0
  - icu=73.2
  - lame=3.100
  - libass=0.17.1
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libtasn1=4.19.0
  - libunistring=0.9.10
  - libvpx=1.13.1
  - libxml2=2.12.3
  - libzlib=1.2.13
  - ncurses=6.4
  - nettle=3.9.1
  - openh264=2.4.0
  - openssl=3.2.0
  - p11-kit=0.24.1
  - pcre2=10.42
  - pip=23.3.2
  - pixman=0.42.2
  - python=3.12.0
  - readline=8.2
  - setuptools=68.2.2
  - svt-av1=1.8.0
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.42.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - zlib=1.2.13