name: Publish Python distributions to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: lkg-quilt
          environment-file: environment.yml
          python-version: 3.12
          auto-activate-base: false

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          conda install setuptools wheel twine -y

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
